name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: yarn install
    - run: yarn build
    - run: yarn lint
    - run: yarn test
